@startuml inference-flow

title Inference Flow


top to bottom direction

set separator none

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

skinparam BackgroundColor black
skinparam DefaultFontColor gold
skinparam ArrowColor gold

System_Boundary(inferenc, "Inference") {
  Container_Boundary(nextjs, "NextJS") {
    Component(dashboard, "Dashboard")
    }

  System_Boundary(aws, "AWS") {
  Component(s3, "S3")

  Container_Boundary(functions, "Lambda") {
    Component(restore, "Restore Image")
    Component(colorize, "Colorize Image")
    Component(save, "save image to S3")
  }

  Component(evt, "Event Bridge")
  }

  System_Boundary(replicate, "Replicate") {
    'model Naihgtmareai/real-esrgan
    Component(restoration, "real-esrgan")
    'model Cjwbw/BigColor
    Component(colorization, "BigColor")
  }

  'upload image and extract enhancment factor and colorization
  dashboard ---> s3: "upload image"
  s3 ---> evt: "image uploaded"

  'restroe image
  skinparam DefaultFontColor white
  skinparam ArrowColor white
  evt ---> restore: "restore image"
  restore ---> restoration: "infer restoration"
  restore <--- restoration: "restored image"
  restore ---> evt: "image restored"

  'colorize image if necessary
  skinparam DefaultFontColor green
  skinparam ArrowColor green
  evt ---> colorize: "colorize image"
  colorize ---> colorization: "infer colorization"
  colorize <--- colorization: "colorized image"
  colorize ---> evt: "image colorized"

  'save image
  skinparam DefaultFontColor gray
  skinparam ArrowColor gray
  evt ---> save: "save image"
  save ---> s3: "saving the image"
  s3 ---> dashboard: "show image"
}

@enduml
