@startuml restoreai

title Restore AI: Overview

left to right direction

set separator none

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

skinparam BackgroundColor black
skinparam DefaultFontColor gold

System_Boundary(restoreai, "Restore AI") {

  System_Boundary(supabase, "Supabase") {
    Container_Boundary(storage, "Storage") {
      Component(upload, "Upload")
      Component(download, "Download")
    }

    Container_Boundary(auth, "Authentication") {
      Component(login, "Login")
      Component(logout, "Logout")
      Component(login, "Login")
      Component(reset, "reset")
    }

    Container_Boundary(db, "database") {
      Component(userdata, "userdata")
    }
  }

  System_Boundary(replicate, "Replicate") {
    Component(gfpgan, "GFPGan")
  }

  System_Boundary(next, "Nextjs frontend") {
    Component(uploader, "Uploader")
  }
}

@enduml
